basePath: /v1
definitions:
  api.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  api.SystemResponse:
    properties:
      data:
        type: object
      message:
        type: string
    type: object
info:
  contact: {}
  description: fxDmx REST service for DMX fixture control from Raspberry Pi
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: fxDmx
  version: "1.0"
paths:
  /event/{id}:
    get:
      consumes:
      - application/json
      description: Gets a log event.
      parameters:
      - description: The event id to get
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SystemResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Gets a log event.
      tags:
      - events
  /events:
    get:
      consumes:
      - application/json
      description: Gets all events in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SystemResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Gets all events in the system
      tags:
      - events
  /timelines:
    get:
      consumes:
      - application/json
      description: List all timelines in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SystemResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: List all timelines in the system
      tags:
      - triggers
swagger: "2.0"
